@echo off
title FreeGames.exe
echo Press any key to install FREE GAMES
pause
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo INSTALLING FREE GAMES PLEASE WAIT!!!
echo Thank yous for installing FREE GAMES!!! press any key to play FREE GAMES!!!
pause